from enum import Enum

class Token(Enum):
    # Tokens genéricos
    ID = "ID"
    NUMERO = "NUMERO"
    STRING = "STRING"
    ATRIBUICAO = "ATRIBUICAO"
    DOIS_PONTOS = "DOIS_PONTOS"
    PONTO_VIRGULA = "PONTO_VIRGULA"
    VIRGULA = "VIRGULA"
    PONTO = "PONTO"
    PARENTESES_ESQ = "PARENTESES_ESQ"
    PARENTESES_DIR = "PARENTESES_DIR"
    COLCHETE_ESQ = "COLCHETE_ESQ"
    COLCHETE_DIR = "COLCHETE_DIR"
    OP_LOGICO = "OP_LOGICO"
    OP_MAT = "OP_MAT"

    # Palavras reservadas
    PROGRAM = "PROGRAM"
    CONST = "CONST"
    TYPE = "TYPE"
    VAR = "VAR"
    FUNCTION = "FUNCTION"
    INTEGER = "INTEGER"
    REAL = "REAL"
    ARRAY = "ARRAY"
    OF = "OF"
    RECORD = "RECORD"
    BEGIN = "BEGIN"
    END = "END"
    WHILE = "WHILE"
    IF = "IF"
    THEN = "THEN"
    ELSE = "ELSE"
    WRITE = "WRITE"
    READ = "READ"
